export const SET_LOADING = 'SET_LOADING';
export const CLEAR_POKEMONS = 'CLEAR_POKEMONS';
export const SET_POKEMONS = 'SET_POKEMONS';
export const SET_TOTAL_OF_POKEMONS = 'SET_TOTAL_OF_POKEMONS';
export const SET_CURRENT_POKEMONS_PAGE = 'SET_CURRENT_POKEMONS_PAGE';
